language: go
go:
  - 1.9
  - tip

install: true
  - go get -u gopkg.in/alecthomas/gometalinter.v1
  - gometalinter --install

script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - test -z $(gofmt -s -l $GO_FILES)
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go vet ./...
  - gometalinter ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)